# Generated by Django 5.2.6 on 2025-10-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('building', models.CharField(max_length=100)),
                ('apartment', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('last_uploaded', models.DateTimeField(auto_now=True)),
                ('client_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('employee_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
