# Generated by Django 5.2.6 on 2025-10-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedashboard', '0002_supervisorformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorformmodel',
            name='performance',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Below Average', 'Below Average'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supervisorformmodel',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
