# Generated by Django 5.2.6 on 2025-10-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedashboard', '0003_supervisorformmodel_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorformmodel',
            name='report_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
