# Generated by Django 5.2.6 on 2025-10-21 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedashboard', '0004_alter_supervisorformmodel_report_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorformmodel',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
