# Generated by Django 5.2.6 on 2025-10-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedashboard', '0005_alter_supervisorformmodel_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorformmodel',
            name='work_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
