services:
  web:
    build: .
    container_name: cleanupbackend_web
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 core.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    ports:
      - "8081:8000"
    env_file:
      - .env
    depends_on:
      - redis

  # nginx:
  #   image: nginx:alpine
  #   container_name: cleanup_nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./static:/app/static
  #   depends_on:
  #     - web

  redis:
    image: redis:7-alpine
    container_name: cleanup_redis
    ports:
      - "6380:6379"

  celery:
    build: .
    container_name: myproject_celery
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web
