# Generated by Django 5.2.6 on 2025-10-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Cleaning', max_length=100)),
                ('role', models.CharField(default='Cleaner', max_length=100)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('id_expiry', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=50)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('On Leave', 'On Leave')], default='Active', max_length=20, null=True)),
                ('contract_start', models.DateField(auto_now_add=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_on_leave', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employee_avatars/')),
                ('salary_day', models.IntegerField(blank=True, null=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('performance_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
