# Generated by Django 5.2.4 on 2025-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeProfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='base_salary',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
