# Generated by Django 5.2.6 on 2025-09-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeProfiles', '0002_remove_employeesalary_base_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('On Leave', 'On Leave')], default='Active', max_length=20, null=True),
        ),
    ]
