# Generated by Django 5.2.6 on 2025-10-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRequestFromEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('expense_date', models.DateField()),
                ('discription', models.TextField()),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Submitted', 'submitted'), ('Approved', 'Approved'), ('Cancel', 'Cancel')], default='Submitted')),
            ],
        ),
    ]
