# Generated by Django 5.2.6 on 2025-09-30 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services_pakages', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRequestFromEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('expense_date', models.DateField()),
                ('discription', models.TextField()),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Submitted', 'submitted'), ('Approved', 'Approved'), ('Cancel', 'Cancel')], default='Submitted')),
                ('expense_category', models.ManyToManyField(to='services_pakages.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
