# Generated by Django 5.2.6 on 2025-10-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice_request_from_client', '0001_initial'),
        ('services_pakages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerequestfromemployee',
            name='expense_category',
            field=models.ManyToManyField(to='services_pakages.category'),
        ),
    ]
