# Generated by Django 5.2.6 on 2025-10-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_request_from_client', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerequestfromemployee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicerequestfromemployee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
