# Generated by Django 5.2.6 on 2025-10-16 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_ratingmodel_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
