# Generated by Django 5.2.6 on 2025-10-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_alter_ratingmodel_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
