# Generated by Django 5.2.6 on 2025-10-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='onetoonechatmassage',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='onetoonechatmassage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
