# Generated by Django 5.2.6 on 2025-10-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicForm', '0003_formsubmissionmodel_response_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formnamemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
