# Generated by Django 5.2.6 on 2025-09-27 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('plan', '0008_alter_subscription_status'),
        ('services_pakages', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignToEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('base_price', models.CharField(max_length=100)),
                ('bill_cycle', models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=100)),
                ('discount', models.CharField(max_length=10)),
                ('auto_renew_enable', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('service_icon', models.ImageField(blank=True, null=True, upload_to='./service/icon')),
                ('status', models.BooleanField(default=True)),
                ('apratment', models.ManyToManyField(to='locations.apartment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.building')),
                ('category', models.ManyToManyField(to='services_pakages.category')),
                ('package', models.ManyToManyField(to='assign_task_employee.featuremodel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plan.planmodel')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
