# Generated by Django 5.2.6 on 2025-10-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assign_task_employee', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialservicesmodel',
            name='apartment',
            field=models.ManyToManyField(related_name='special_services_apartments', to='locations.apartment'),
        ),
        migrations.AddField(
            model_name='specialservicesmodel',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.building'),
        ),
    ]
