# Generated by Django 5.2.6 on 2025-10-01 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assign_task_employee', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigntoemployee',
            name='apratment',
            field=models.ManyToManyField(to='locations.apartment'),
        ),
        migrations.AddField(
            model_name='taskassigntoemployee',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.building'),
        ),
    ]
