# Generated by Django 5.2.6 on 2025-09-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigntoemployee',
            name='tax_rate',
            field=models.CharField(blank=True, null=True),
        ),
    ]
