# Generated by Django 5.2.6 on 2025-09-24 23:40

import django.db.models.deletion
import services_pakages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigntoemployee',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.building'),
        ),
        migrations.AlterField(
            model_name='taskassigntoemployee',
            name='apratment',
            field=models.ManyToManyField(blank=True, null=True, to='locations.apartment'),
        ),
        migrations.AlterField(
            model_name='taskassigntoemployee',
            name='category',
            field=models.CharField(verbose_name=services_pakages.models.Category),
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
