# Generated by Django 5.2.6 on 2025-10-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assign_task_employee', '0002_initial'),
        ('locations', '0001_initial'),
        ('services_pakages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialservicesmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services_pakages.category'),
        ),
        migrations.AddField(
            model_name='specialservicesmodel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.region'),
        ),
    ]
