# Generated by Django 5.2.6 on 2025-09-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0002_alter_taskassigntoemployee_building_and_more'),
        ('services_pakages', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassigntoemployee',
            name='category',
        ),
        migrations.AddField(
            model_name='taskassigntoemployee',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='services_pakages.category'),
        ),
    ]
