# Generated by Django 5.2.6 on 2025-09-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigntoemployee',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('started', 'started'), ('canceled', 'canceled')], null=True),
        ),
    ]
