# Generated by Django 5.2.6 on 2025-09-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0002_taskassigntoemployee_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigntoemployee',
            name='discount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
