# Generated by Django 5.2.6 on 2025-10-01 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assign_task_employee', '0002_initial'),
        ('plan', '0001_initial'),
        ('services_pakages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigntoemployee',
            name='category',
            field=models.ManyToManyField(to='services_pakages.category'),
        ),
        migrations.AddField(
            model_name='taskassigntoemployee',
            name='package',
            field=models.ManyToManyField(to='assign_task_employee.featuremodel'),
        ),
        migrations.AddField(
            model_name='taskassigntoemployee',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plan.planmodel'),
        ),
    ]
