# Generated by Django 5.2.6 on 2025-09-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0003_remove_taskassigntoemployee_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigntoemployee',
            name='service_icon',
            field=models.ImageField(blank=True, null=True, upload_to='./service/icon'),
        ),
        migrations.AddField(
            model_name='taskassigntoemployee',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
