# Generated by Django 5.2.6 on 2025-09-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0003_alter_taskassigntoemployee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigntoemployee',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('started', 'started'), ('canceled', 'canceled'), ('pending', 'pending')], default='pending', null=True),
        ),
    ]
