# Generated by Django 5.2.6 on 2025-10-09 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0004_initial'),
        ('locations', '0002_initial'),
        ('services_pakages', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_code', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('base_price', models.CharField(max_length=100)),
                ('bill_cycle', models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=100)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('auto_renew_enable', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('service_icon', models.ImageField(blank=True, null=True, upload_to='./service/icon')),
                ('tax_rate', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('completed', 'completed'), ('started', 'started'), ('canceled', 'canceled'), ('pending', 'pending')], default='pending', null=True)),
                ('apratment', models.ManyToManyField(to='locations.apartment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.building')),
                ('category', models.ManyToManyField(to='services_pakages.category')),
                ('package', models.ManyToManyField(to='assign_task_employee.featuremodel')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.region')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskAssignToEmployee',
        ),
    ]
