# Generated by Django 5.2.6 on 2025-09-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0004_taskassigntoemployee_service_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassigntoemployee',
            old_name='task_code',
            new_name='service_code',
        ),
    ]
