# Generated by Django 5.2.6 on 2025-10-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialservicesmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialservicesmodel',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
