# Generated by Django 5.2.6 on 2025-10-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0005_specialservicesmodel_delete_taskassigntoemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialservicesmodel',
            name='package',
        ),
    ]
