# Generated by Django 5.2.6 on 2025-10-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0006_remove_specialservicesmodel_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialservicesmodel',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialservicesmodel',
            name='base_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='specialservicesmodel',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
