# Generated by Django 5.2.6 on 2025-10-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0006_ratingmodelforservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodelforservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ratingmodelforservice',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
