# Generated by Django 5.2.6 on 2025-10-09 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0007_specialservicesmodel_discounted_price_and_more'),
        ('services_pakages', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialservicesmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='specialservicesmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services_pakages.category'),
        ),
    ]
