# Generated by Django 5.2.6 on 2025-10-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0007_ratingmodelforservice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialservicesmodel',
            name='bill_cycle',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=100),
        ),
    ]
