# Generated by Django 5.2.6 on 2025-10-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0008_remove_specialservicesmodel_category_and_more'),
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialservicesmodel',
            name='apratment',
            field=models.ManyToManyField(related_name='special_services_apartments', to='locations.apartment'),
        ),
    ]
