# Generated by Django 5.2.6 on 2025-10-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0009_alter_specialservicesmodel_apratment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialservicesmodel',
            old_name='apratment',
            new_name='apartment',
        ),
    ]
