# Generated by Django 5.2.6 on 2025-10-31 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0008_alter_specialservicesmodel_bill_cycle'),
        ('client_dashboard', '0001_initial'),
        ('plan', '0006_alter_invoicemodel_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcheckoutform',
            name='special_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assign_task_employee.specialservicesmodel'),
        ),
        migrations.AlterField(
            model_name='clientcheckoutform',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientcheckoutform',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.subscription'),
        ),
    ]
