# Generated by Django 5.2.6 on 2025-11-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_dashboard', '0002_clientcheckoutform_special_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcheckoutform',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='clientcheckoutform',
            name='client_set_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
