# Generated by Django 5.2.6 on 2025-10-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
