# Generated by Django 5.2.6 on 2025-09-29 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0004_alter_taskassigntoemployee_status'),
        ('locations', '0001_initial'),
        ('plan', '0002_alter_subscription_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('outgoing', 'Outgoing (Sales)'), ('incoming', 'Incoming (Expenses)')], max_length=20)),
                ('date_issued', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('vendor_invoice_file', models.FileField(blank=True, null=True, upload_to='vendor_invoices')),
                ('note', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='invoices')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apartments', models.ManyToManyField(to='locations.apartment')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.building')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.planmodel')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assign_task_employee.featuremodel')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='plan.invoicemodel')),
            ],
        ),
    ]
