# Generated by Django 5.2.6 on 2025-09-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_invoicemodel_invoicelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('unpaid', 'unpaid')], null=True),
        ),
    ]
