# Generated by Django 5.2.6 on 2025-10-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_invoicelineitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmodel',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
    ]
