# Generated by Django 5.2.6 on 2025-09-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_subscription_apartment_subscription_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_permanently_stopped',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='pause_until',
        ),
    ]
