# Generated by Django 5.2.6 on 2025-10-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_subscription_canceled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
