# Generated by Django 5.2.6 on 2025-10-08 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0004_initial'),
        ('plan', '0004_remove_planmodel_stripe_price_id_and_more'),
        ('services_pakages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services_pakages.category'),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='package',
            field=models.ManyToManyField(to='assign_task_employee.featuremodel'),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('day', 'Daily')], default='month', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('past_due', 'past_due')], default='active', max_length=20),
        ),
    ]
