# Generated by Django 5.2.6 on 2025-10-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_subscription_next_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='next_payment_date',
        ),
    ]
