# Generated by Django 5.2.6 on 2025-09-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_invoicemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='auto_renewal',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='discount',
            field=models.CharField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
