# Generated by Django 5.2.6 on 2025-09-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_planmodel_auto_renewal_planmodel_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='vendor_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
