# Generated by Django 5.2.6 on 2025-10-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_planmodel_category_planmodel_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmodel',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
