# Generated by Django 5.2.6 on 2025-09-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_subscription_created_at_subscription_pause_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('paused', 'Paused'), ('canceled', 'Canceled')], default='inactive', max_length=20),
        ),
    ]
