# Generated by Django 5.2.6 on 2025-10-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_task_employee', '0004_initial'),
        ('plan', '0006_alter_planmodel_amount_alter_planmodel_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmodel',
            name='package',
            field=models.ManyToManyField(blank=True, to='assign_task_employee.featuremodel'),
        ),
    ]
