# Generated by Django 5.2.6 on 2025-09-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_invoicemodel_vendor_name_alter_planmodel_discount'),
        ('services_pakages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='expense_category',
            field=models.ManyToManyField(to='services_pakages.category'),
        ),
    ]
