# Generated by Django 5.2.6 on 2025-09-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_subscription_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('past_due', 'past_due')], default='inactive', max_length=20),
        ),
    ]
