# Generated by Django 5.2.6 on 2025-10-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_servicelineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmodel',
            name='package',
        ),
    ]
