# Generated by Django 5.2.6 on 2025-10-09 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_subscription_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='employee',
            field=models.ManyToManyField(related_name='subscription_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
