# Generated by Django 5.2.6 on 2025-10-09 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
        ('plan', '0011_subscription_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_services', to='locations.apartment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_services', to='locations.building')),
            ],
        ),
    ]
