# Generated by Django 5.2.6 on 2025-10-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_remove_subscription_end_date_and_more'),
        ('services_pakages', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='expense_category',
            field=models.ManyToManyField(blank=True, to='services_pakages.category'),
        ),
    ]
