# Generated by Django 5.2.6 on 2025-10-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0014_alter_invoicemodel_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='service',
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
