# Generated by Django 5.2.6 on 2025-10-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_remove_invoicelineitem_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
