# Generated by Django 5.2.6 on 2025-10-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_alter_invoicelineitem_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
