# Generated by Django 5.2.6 on 2025-10-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0017_invoicemodel_created_at_invoicemodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
