# Generated by Django 5.2.6 on 2025-10-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_alter_invoicemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
