# Generated by Django 5.2.6 on 2025-10-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_invoicelineitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='total',
        ),
    ]
