# Generated by Django 5.2.6 on 2025-10-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0020_remove_invoicelineitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='subtotal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='subtotal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
