# Generated by Django 5.2.6 on 2025-10-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0021_invoicelineitem_subtotal_invoicemodel_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicemodel',
            old_name='subtotal',
            new_name='sub_total',
        ),
    ]
