# Generated by Django 5.2.6 on 2025-10-11 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0022_rename_subtotal_invoicemodel_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='subtotal',
            new_name='sub_total',
        ),
    ]
