# Generated by Django 5.2.6 on 2025-10-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0023_rename_subtotal_invoicelineitem_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='past_due_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
