# Generated by Django 5.2.6 on 2025-10-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0024_subscription_past_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
