# Generated by Django 5.2.6 on 2025-10-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0025_subscription_canceled_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='past_due_date',
            new_name='paused_at',
        ),
    ]
