# Generated by Django 5.2.6 on 2025-09-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
