# Generated by Django 5.2.6 on 2025-10-14 21:02

import locations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('living_rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('outdoor_area', models.BooleanField(default=False)),
                ('postcode', models.CharField(max_length=5, validators=[locations.models.validate_saudi_postcode])),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, default=24.7136, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=46.6753, max_digits=9)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
    ]
