# Generated by Django 5.2.6 on 2025-11-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_building_latitude_alter_building_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.CharField(blank=True, null=True),
        ),
    ]
