# Generated by Django 5.2.6 on 2025-10-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_building_latitude_alter_building_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='client_code_with_region_code',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='client_code_with_region_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),

        
    ]
