# Generated by Django 5.2.6 on 2025-10-30 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_apartment_client_code_with_region_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='client_code_with_region_code',
            new_name='apartment_code',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='client_code_with_region_name',
            new_name='apartment_code2',
        ),
    ]
