# Generated by Django 5.2.6 on 2026-01-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_apartment_floor'),
        ('locations', '0006_rename_client_code_with_region_code_apartment_apartment_code_and_more'),
    ]

    operations = [
    ]
