# Generated by Django 5.2.6 on 2025-09-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_pakages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='billing_cycle',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
