# Generated by Django 5.2.6 on 2025-10-01 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services_pakages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceassignment',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='employees',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'employee'}, related_name='service_works', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services_pakages.package'),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services_pakages.service'),
        ),
    ]
