# Generated by Django 5.2.6 on 2025-10-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='for_all',
            field=models.BooleanField(default=False),
        ),
    ]
